// Code generated by protoc-gen-go. DO NOT EDIT.
// source: command.proto

package PBCommand

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Robot_Command struct {
	LeftVel              *float32 `protobuf:"fixed32,1,req,name=left_vel,json=leftVel" json:"left_vel,omitempty"`
	RightVel             *float32 `protobuf:"fixed32,2,req,name=right_vel,json=rightVel" json:"right_vel,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Robot_Command) Reset()         { *m = Robot_Command{} }
func (m *Robot_Command) String() string { return proto.CompactTextString(m) }
func (*Robot_Command) ProtoMessage()    {}
func (*Robot_Command) Descriptor() ([]byte, []int) {
	return fileDescriptor_213c0bb044472049, []int{0}
}

func (m *Robot_Command) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Robot_Command.Unmarshal(m, b)
}
func (m *Robot_Command) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Robot_Command.Marshal(b, m, deterministic)
}
func (m *Robot_Command) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Robot_Command.Merge(m, src)
}
func (m *Robot_Command) XXX_Size() int {
	return xxx_messageInfo_Robot_Command.Size(m)
}
func (m *Robot_Command) XXX_DiscardUnknown() {
	xxx_messageInfo_Robot_Command.DiscardUnknown(m)
}

var xxx_messageInfo_Robot_Command proto.InternalMessageInfo

func (m *Robot_Command) GetLeftVel() float32 {
	if m != nil && m.LeftVel != nil {
		return *m.LeftVel
	}
	return 0
}

func (m *Robot_Command) GetRightVel() float32 {
	if m != nil && m.RightVel != nil {
		return *m.RightVel
	}
	return 0
}

type Global_Commands struct {
	RobotCommands        []*Robot_Command `protobuf:"bytes,1,rep,name=robot_commands,json=robotCommands" json:"robot_commands,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Global_Commands) Reset()         { *m = Global_Commands{} }
func (m *Global_Commands) String() string { return proto.CompactTextString(m) }
func (*Global_Commands) ProtoMessage()    {}
func (*Global_Commands) Descriptor() ([]byte, []int) {
	return fileDescriptor_213c0bb044472049, []int{1}
}

func (m *Global_Commands) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Global_Commands.Unmarshal(m, b)
}
func (m *Global_Commands) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Global_Commands.Marshal(b, m, deterministic)
}
func (m *Global_Commands) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Global_Commands.Merge(m, src)
}
func (m *Global_Commands) XXX_Size() int {
	return xxx_messageInfo_Global_Commands.Size(m)
}
func (m *Global_Commands) XXX_DiscardUnknown() {
	xxx_messageInfo_Global_Commands.DiscardUnknown(m)
}

var xxx_messageInfo_Global_Commands proto.InternalMessageInfo

func (m *Global_Commands) GetRobotCommands() []*Robot_Command {
	if m != nil {
		return m.RobotCommands
	}
	return nil
}

func init() {
	proto.RegisterType((*Robot_Command)(nil), "PBCommand.Robot_Command")
	proto.RegisterType((*Global_Commands)(nil), "PBCommand.Global_Commands")
}

func init() {
	proto.RegisterFile("command.proto", fileDescriptor_213c0bb044472049)
}

var fileDescriptor_213c0bb044472049 = []byte{
	// 145 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0xce, 0xcf, 0xcd,
	0x4d, 0xcc, 0x4b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x0c, 0x70, 0x72, 0x86, 0x08,
	0x28, 0xb9, 0x73, 0xf1, 0x06, 0xe5, 0x27, 0xe5, 0x97, 0xc4, 0x43, 0x05, 0x84, 0x24, 0xb9, 0x38,
	0x72, 0x52, 0xd3, 0x4a, 0xe2, 0xcb, 0x52, 0x73, 0x24, 0x18, 0x15, 0x98, 0x34, 0x98, 0x82, 0xd8,
	0x41, 0xfc, 0xb0, 0xd4, 0x1c, 0x21, 0x69, 0x2e, 0xce, 0xa2, 0xcc, 0xf4, 0x0c, 0x88, 0x1c, 0x13,
	0x58, 0x8e, 0x03, 0x2c, 0x10, 0x96, 0x9a, 0xa3, 0x14, 0xc4, 0xc5, 0xef, 0x9e, 0x93, 0x9f, 0x94,
	0x98, 0x03, 0x33, 0xa9, 0x58, 0xc8, 0x9e, 0x8b, 0xaf, 0x08, 0x6c, 0x36, 0xd4, 0xf6, 0x62, 0x09,
	0x46, 0x05, 0x66, 0x0d, 0x6e, 0x23, 0x09, 0x3d, 0xb8, 0xfd, 0x7a, 0x28, 0x96, 0x07, 0xf1, 0x82,
	0xd5, 0xc3, 0x0c, 0x00, 0x04, 0x00, 0x00, 0xff, 0xff, 0x86, 0xed, 0x66, 0x6a, 0xb7, 0x00, 0x00,
	0x00,
}
