// Code generated by protoc-gen-go. DO NOT EDIT.
// source: control.proto

package PBControl

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Pose struct {
	X                    *float32 `protobuf:"fixed32,1,req,name=x" json:"x,omitempty"`
	Y                    *float32 `protobuf:"fixed32,2,req,name=y" json:"y,omitempty"`
	Yaw                  *float32 `protobuf:"fixed32,3,opt,name=yaw" json:"yaw,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pose) Reset()         { *m = Pose{} }
func (m *Pose) String() string { return proto.CompactTextString(m) }
func (*Pose) ProtoMessage()    {}
func (*Pose) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c5120591600887d, []int{0}
}

func (m *Pose) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pose.Unmarshal(m, b)
}
func (m *Pose) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pose.Marshal(b, m, deterministic)
}
func (m *Pose) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pose.Merge(m, src)
}
func (m *Pose) XXX_Size() int {
	return xxx_messageInfo_Pose.Size(m)
}
func (m *Pose) XXX_DiscardUnknown() {
	xxx_messageInfo_Pose.DiscardUnknown(m)
}

var xxx_messageInfo_Pose proto.InternalMessageInfo

func (m *Pose) GetX() float32 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

func (m *Pose) GetY() float32 {
	if m != nil && m.Y != nil {
		return *m.Y
	}
	return 0
}

func (m *Pose) GetYaw() float32 {
	if m != nil && m.Yaw != nil {
		return *m.Yaw
	}
	return 0
}

type User_Control struct {
	Paused               *bool    `protobuf:"varint,1,opt,name=paused" json:"paused,omitempty"`
	NewBallPose          *Pose    `protobuf:"bytes,2,opt,name=new_ball_pose,json=newBallPose" json:"new_ball_pose,omitempty"`
	NewRobotsBluePose    []*Pose  `protobuf:"bytes,3,rep,name=new_robots_blue_pose,json=newRobotsBluePose" json:"new_robots_blue_pose,omitempty"`
	NewRobotsYellowPose  []*Pose  `protobuf:"bytes,4,rep,name=new_robots_yellow_pose,json=newRobotsYellowPose" json:"new_robots_yellow_pose,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User_Control) Reset()         { *m = User_Control{} }
func (m *User_Control) String() string { return proto.CompactTextString(m) }
func (*User_Control) ProtoMessage()    {}
func (*User_Control) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c5120591600887d, []int{1}
}

func (m *User_Control) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User_Control.Unmarshal(m, b)
}
func (m *User_Control) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User_Control.Marshal(b, m, deterministic)
}
func (m *User_Control) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User_Control.Merge(m, src)
}
func (m *User_Control) XXX_Size() int {
	return xxx_messageInfo_User_Control.Size(m)
}
func (m *User_Control) XXX_DiscardUnknown() {
	xxx_messageInfo_User_Control.DiscardUnknown(m)
}

var xxx_messageInfo_User_Control proto.InternalMessageInfo

func (m *User_Control) GetPaused() bool {
	if m != nil && m.Paused != nil {
		return *m.Paused
	}
	return false
}

func (m *User_Control) GetNewBallPose() *Pose {
	if m != nil {
		return m.NewBallPose
	}
	return nil
}

func (m *User_Control) GetNewRobotsBluePose() []*Pose {
	if m != nil {
		return m.NewRobotsBluePose
	}
	return nil
}

func (m *User_Control) GetNewRobotsYellowPose() []*Pose {
	if m != nil {
		return m.NewRobotsYellowPose
	}
	return nil
}

func init() {
	proto.RegisterType((*Pose)(nil), "PBControl.Pose")
	proto.RegisterType((*User_Control)(nil), "PBControl.User_Control")
}

func init() {
	proto.RegisterFile("control.proto", fileDescriptor_0c5120591600887d)
}

var fileDescriptor_0c5120591600887d = []byte{
	// 222 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x8e, 0xc1, 0x4e, 0xc3, 0x30,
	0x10, 0x44, 0xb5, 0x4e, 0x85, 0x60, 0xdb, 0x0a, 0x30, 0xa8, 0xf2, 0xd1, 0xea, 0x29, 0xa7, 0x1c,
	0x80, 0x0f, 0x40, 0x81, 0x0f, 0xa8, 0x2c, 0x71, 0xe0, 0x14, 0x25, 0xb0, 0xb7, 0x55, 0x36, 0x8a,
	0x13, 0xb9, 0xf9, 0x5e, 0x7e, 0x04, 0xd9, 0xae, 0xaa, 0x1e, 0x7a, 0xdb, 0x19, 0xcd, 0xbc, 0x1d,
	0xdc, 0xfe, 0x48, 0x3f, 0x8d, 0xc2, 0xd5, 0x30, 0xca, 0x24, 0xfa, 0xee, 0x50, 0x7f, 0x64, 0x63,
	0xff, 0x86, 0xab, 0x83, 0x78, 0xd2, 0x1b, 0x84, 0xa3, 0x01, 0xab, 0x4a, 0xe5, 0xe0, 0x18, 0xd5,
	0x62, 0x54, 0x56, 0x8b, 0x7e, 0xc0, 0x62, 0x69, 0x83, 0x29, 0x2c, 0x94, 0xca, 0xc5, 0x73, 0xff,
	0x07, 0xb8, 0xf9, 0xf2, 0x34, 0x36, 0x27, 0x8c, 0xde, 0xe1, 0xcd, 0xd0, 0xce, 0x9e, 0x7e, 0x0d,
	0x58, 0x28, 0x6f, 0xdd, 0x49, 0xe9, 0x57, 0xdc, 0xf6, 0x14, 0x9a, 0xae, 0x65, 0x6e, 0x06, 0xf1,
	0x64, 0x94, 0x85, 0x72, 0xfd, 0x72, 0x5f, 0x9d, 0x17, 0x54, 0xf1, 0xbd, 0x5b, 0xf7, 0x14, 0xea,
	0x96, 0x39, 0x6d, 0x79, 0xc7, 0xe7, 0x58, 0x1a, 0xa5, 0x93, 0xc9, 0x37, 0x1d, 0xcf, 0x94, 0xbb,
	0x85, 0x2d, 0xae, 0x75, 0x1f, 0x7b, 0x0a, 0x2e, 0x65, 0x6b, 0x9e, 0x29, 0x11, 0x3e, 0x71, 0x77,
	0x41, 0x58, 0x88, 0x59, 0x42, 0x66, 0xac, 0xae, 0x33, 0x9e, 0xce, 0x8c, 0xef, 0x14, 0x8e, 0xe6,
	0x7f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x8d, 0x9e, 0x62, 0x5f, 0x36, 0x01, 0x00, 0x00,
}
