// Code generated by protoc-gen-go. DO NOT EDIT.
// source: state.proto

package PBState

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Pose struct {
	X                    *float32 `protobuf:"fixed32,1,req,name=x" json:"x,omitempty"`
	Y                    *float32 `protobuf:"fixed32,2,req,name=y" json:"y,omitempty"`
	Yaw                  *float32 `protobuf:"fixed32,3,opt,name=yaw" json:"yaw,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pose) Reset()         { *m = Pose{} }
func (m *Pose) String() string { return proto.CompactTextString(m) }
func (*Pose) ProtoMessage()    {}
func (*Pose) Descriptor() ([]byte, []int) {
	return fileDescriptor_a888679467bb7853, []int{0}
}

func (m *Pose) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pose.Unmarshal(m, b)
}
func (m *Pose) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pose.Marshal(b, m, deterministic)
}
func (m *Pose) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pose.Merge(m, src)
}
func (m *Pose) XXX_Size() int {
	return xxx_messageInfo_Pose.Size(m)
}
func (m *Pose) XXX_DiscardUnknown() {
	xxx_messageInfo_Pose.DiscardUnknown(m)
}

var xxx_messageInfo_Pose proto.InternalMessageInfo

func (m *Pose) GetX() float32 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

func (m *Pose) GetY() float32 {
	if m != nil && m.Y != nil {
		return *m.Y
	}
	return 0
}

func (m *Pose) GetYaw() float32 {
	if m != nil && m.Yaw != nil {
		return *m.Yaw
	}
	return 0
}

type Ball_State struct {
	Pose                 *Pose    `protobuf:"bytes,1,req,name=pose" json:"pose,omitempty"`
	VPose                *Pose    `protobuf:"bytes,2,opt,name=v_pose,json=vPose" json:"v_pose,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ball_State) Reset()         { *m = Ball_State{} }
func (m *Ball_State) String() string { return proto.CompactTextString(m) }
func (*Ball_State) ProtoMessage()    {}
func (*Ball_State) Descriptor() ([]byte, []int) {
	return fileDescriptor_a888679467bb7853, []int{1}
}

func (m *Ball_State) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ball_State.Unmarshal(m, b)
}
func (m *Ball_State) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ball_State.Marshal(b, m, deterministic)
}
func (m *Ball_State) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ball_State.Merge(m, src)
}
func (m *Ball_State) XXX_Size() int {
	return xxx_messageInfo_Ball_State.Size(m)
}
func (m *Ball_State) XXX_DiscardUnknown() {
	xxx_messageInfo_Ball_State.DiscardUnknown(m)
}

var xxx_messageInfo_Ball_State proto.InternalMessageInfo

func (m *Ball_State) GetPose() *Pose {
	if m != nil {
		return m.Pose
	}
	return nil
}

func (m *Ball_State) GetVPose() *Pose {
	if m != nil {
		return m.VPose
	}
	return nil
}

type Robot_State struct {
	Pose                 *Pose    `protobuf:"bytes,1,req,name=pose" json:"pose,omitempty"`
	VPose                *Pose    `protobuf:"bytes,2,opt,name=v_pose,json=vPose" json:"v_pose,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Robot_State) Reset()         { *m = Robot_State{} }
func (m *Robot_State) String() string { return proto.CompactTextString(m) }
func (*Robot_State) ProtoMessage()    {}
func (*Robot_State) Descriptor() ([]byte, []int) {
	return fileDescriptor_a888679467bb7853, []int{2}
}

func (m *Robot_State) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Robot_State.Unmarshal(m, b)
}
func (m *Robot_State) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Robot_State.Marshal(b, m, deterministic)
}
func (m *Robot_State) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Robot_State.Merge(m, src)
}
func (m *Robot_State) XXX_Size() int {
	return xxx_messageInfo_Robot_State.Size(m)
}
func (m *Robot_State) XXX_DiscardUnknown() {
	xxx_messageInfo_Robot_State.DiscardUnknown(m)
}

var xxx_messageInfo_Robot_State proto.InternalMessageInfo

func (m *Robot_State) GetPose() *Pose {
	if m != nil {
		return m.Pose
	}
	return nil
}

func (m *Robot_State) GetVPose() *Pose {
	if m != nil {
		return m.VPose
	}
	return nil
}

type Global_State struct {
	Balls                []*Ball_State  `protobuf:"bytes,1,rep,name=balls" json:"balls,omitempty"`
	RobotsYellow         []*Robot_State `protobuf:"bytes,2,rep,name=robots_yellow,json=robotsYellow" json:"robots_yellow,omitempty"`
	RobotsBlue           []*Robot_State `protobuf:"bytes,3,rep,name=robots_blue,json=robotsBlue" json:"robots_blue,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Global_State) Reset()         { *m = Global_State{} }
func (m *Global_State) String() string { return proto.CompactTextString(m) }
func (*Global_State) ProtoMessage()    {}
func (*Global_State) Descriptor() ([]byte, []int) {
	return fileDescriptor_a888679467bb7853, []int{3}
}

func (m *Global_State) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Global_State.Unmarshal(m, b)
}
func (m *Global_State) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Global_State.Marshal(b, m, deterministic)
}
func (m *Global_State) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Global_State.Merge(m, src)
}
func (m *Global_State) XXX_Size() int {
	return xxx_messageInfo_Global_State.Size(m)
}
func (m *Global_State) XXX_DiscardUnknown() {
	xxx_messageInfo_Global_State.DiscardUnknown(m)
}

var xxx_messageInfo_Global_State proto.InternalMessageInfo

func (m *Global_State) GetBalls() []*Ball_State {
	if m != nil {
		return m.Balls
	}
	return nil
}

func (m *Global_State) GetRobotsYellow() []*Robot_State {
	if m != nil {
		return m.RobotsYellow
	}
	return nil
}

func (m *Global_State) GetRobotsBlue() []*Robot_State {
	if m != nil {
		return m.RobotsBlue
	}
	return nil
}

func init() {
	proto.RegisterType((*Pose)(nil), "PBState.Pose")
	proto.RegisterType((*Ball_State)(nil), "PBState.Ball_State")
	proto.RegisterType((*Robot_State)(nil), "PBState.Robot_State")
	proto.RegisterType((*Global_State)(nil), "PBState.Global_State")
}

func init() {
	proto.RegisterFile("state.proto", fileDescriptor_a888679467bb7853)
}

var fileDescriptor_a888679467bb7853 = []byte{
	// 233 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x8f, 0xbd, 0x4a, 0x04, 0x31,
	0x14, 0x85, 0x49, 0x66, 0x57, 0xe1, 0x66, 0x16, 0x24, 0x5a, 0xa4, 0x8c, 0x83, 0xc5, 0xd8, 0x4c,
	0xb1, 0x68, 0x61, 0x3b, 0x8d, 0xed, 0x12, 0x51, 0xb0, 0x1a, 0x12, 0x48, 0x77, 0xe1, 0x2e, 0x9b,
	0xec, 0x4f, 0x9e, 0xc9, 0x97, 0x94, 0x24, 0xeb, 0x28, 0x08, 0x56, 0x56, 0xc9, 0x21, 0xdf, 0x77,
	0x38, 0x01, 0x11, 0xa2, 0x8d, 0x7e, 0xd8, 0xee, 0x28, 0x92, 0xbc, 0xdc, 0x8c, 0x2f, 0x39, 0x76,
	0x0f, 0xb0, 0xd8, 0x50, 0xf0, 0xb2, 0x05, 0x76, 0x52, 0x4c, 0xf3, 0x9e, 0x1b, 0x76, 0xca, 0x29,
	0x29, 0x5e, 0x53, 0x92, 0x57, 0xd0, 0x24, 0x7b, 0x54, 0x8d, 0x66, 0x3d, 0x37, 0xf9, 0xda, 0xbd,
	0x02, 0x8c, 0x16, 0x71, 0x2a, 0x1d, 0xf2, 0x16, 0x16, 0x5b, 0x0a, 0xbe, 0xe8, 0x62, 0xbd, 0x1a,
	0xce, 0xdd, 0x43, 0x2e, 0x36, 0xe5, 0x49, 0xde, 0xc1, 0xc5, 0x61, 0x2a, 0x10, 0xd7, 0xec, 0x37,
	0xb4, 0x3c, 0xe4, 0xa3, 0x7b, 0x03, 0x61, 0xc8, 0x51, 0xfc, 0xef, 0xde, 0x0f, 0x06, 0xed, 0x33,
	0x92, 0xb3, 0x5f, 0x8b, 0xef, 0x61, 0xe9, 0x2c, 0x62, 0x50, 0x4c, 0x37, 0xbd, 0x58, 0x5f, 0xcf,
	0xd6, 0xf7, 0xaf, 0x4c, 0x25, 0xe4, 0x13, 0xac, 0x76, 0x79, 0x53, 0x98, 0x92, 0x47, 0xa4, 0xa3,
	0xe2, 0x45, 0xb9, 0x99, 0x95, 0x1f, 0x8b, 0x4d, 0x5b, 0xd1, 0xf7, 0x42, 0xca, 0x47, 0x10, 0x67,
	0xd5, 0xe1, 0xde, 0xab, 0xe6, 0x0f, 0x11, 0x2a, 0x38, 0xe2, 0xde, 0x7f, 0x06, 0x00, 0x00, 0xff,
	0xff, 0x29, 0xe9, 0xe4, 0x42, 0xa9, 0x01, 0x00, 0x00,
}
