// Code generated by protoc-gen-go. DO NOT EDIT.
// source: debug.proto

package PBDebug

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Pose struct {
	X                    *float32 `protobuf:"fixed32,1,req,name=x" json:"x,omitempty"`
	Y                    *float32 `protobuf:"fixed32,2,req,name=y" json:"y,omitempty"`
	Yaw                  *float32 `protobuf:"fixed32,3,opt,name=yaw" json:"yaw,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pose) Reset()         { *m = Pose{} }
func (m *Pose) String() string { return proto.CompactTextString(m) }
func (*Pose) ProtoMessage()    {}
func (*Pose) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d9d361be58531fb, []int{0}
}

func (m *Pose) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pose.Unmarshal(m, b)
}
func (m *Pose) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pose.Marshal(b, m, deterministic)
}
func (m *Pose) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pose.Merge(m, src)
}
func (m *Pose) XXX_Size() int {
	return xxx_messageInfo_Pose.Size(m)
}
func (m *Pose) XXX_DiscardUnknown() {
	xxx_messageInfo_Pose.DiscardUnknown(m)
}

var xxx_messageInfo_Pose proto.InternalMessageInfo

func (m *Pose) GetX() float32 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

func (m *Pose) GetY() float32 {
	if m != nil && m.Y != nil {
		return *m.Y
	}
	return 0
}

func (m *Pose) GetYaw() float32 {
	if m != nil && m.Yaw != nil {
		return *m.Yaw
	}
	return 0
}

type Path struct {
	Poses                []*Pose  `protobuf:"bytes,1,rep,name=poses" json:"poses,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Path) Reset()         { *m = Path{} }
func (m *Path) String() string { return proto.CompactTextString(m) }
func (*Path) ProtoMessage()    {}
func (*Path) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d9d361be58531fb, []int{1}
}

func (m *Path) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Path.Unmarshal(m, b)
}
func (m *Path) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Path.Marshal(b, m, deterministic)
}
func (m *Path) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Path.Merge(m, src)
}
func (m *Path) XXX_Size() int {
	return xxx_messageInfo_Path.Size(m)
}
func (m *Path) XXX_DiscardUnknown() {
	xxx_messageInfo_Path.DiscardUnknown(m)
}

var xxx_messageInfo_Path proto.InternalMessageInfo

func (m *Path) GetPoses() []*Pose {
	if m != nil {
		return m.Poses
	}
	return nil
}

type Global_Debug struct {
	StepPoses            []*Pose  `protobuf:"bytes,1,rep,name=step_poses,json=stepPoses" json:"step_poses,omitempty"`
	FinalPoses           []*Pose  `protobuf:"bytes,2,rep,name=final_poses,json=finalPoses" json:"final_poses,omitempty"`
	Paths                []*Path  `protobuf:"bytes,3,rep,name=paths" json:"paths,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Global_Debug) Reset()         { *m = Global_Debug{} }
func (m *Global_Debug) String() string { return proto.CompactTextString(m) }
func (*Global_Debug) ProtoMessage()    {}
func (*Global_Debug) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d9d361be58531fb, []int{2}
}

func (m *Global_Debug) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Global_Debug.Unmarshal(m, b)
}
func (m *Global_Debug) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Global_Debug.Marshal(b, m, deterministic)
}
func (m *Global_Debug) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Global_Debug.Merge(m, src)
}
func (m *Global_Debug) XXX_Size() int {
	return xxx_messageInfo_Global_Debug.Size(m)
}
func (m *Global_Debug) XXX_DiscardUnknown() {
	xxx_messageInfo_Global_Debug.DiscardUnknown(m)
}

var xxx_messageInfo_Global_Debug proto.InternalMessageInfo

func (m *Global_Debug) GetStepPoses() []*Pose {
	if m != nil {
		return m.StepPoses
	}
	return nil
}

func (m *Global_Debug) GetFinalPoses() []*Pose {
	if m != nil {
		return m.FinalPoses
	}
	return nil
}

func (m *Global_Debug) GetPaths() []*Path {
	if m != nil {
		return m.Paths
	}
	return nil
}

func init() {
	proto.RegisterType((*Pose)(nil), "PBDebug.Pose")
	proto.RegisterType((*Path)(nil), "PBDebug.Path")
	proto.RegisterType((*Global_Debug)(nil), "PBDebug.Global_Debug")
}

func init() {
	proto.RegisterFile("debug.proto", fileDescriptor_8d9d361be58531fb)
}

var fileDescriptor_8d9d361be58531fb = []byte{
	// 188 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x8e, 0x41, 0x0a, 0xc2, 0x30,
	0x10, 0x45, 0x49, 0x52, 0x11, 0xa7, 0x15, 0x24, 0xab, 0x2c, 0x4b, 0xdd, 0x14, 0x94, 0x2c, 0xc4,
	0x13, 0x88, 0xe0, 0xb6, 0xe4, 0x02, 0x25, 0xc5, 0x68, 0x85, 0x62, 0x8a, 0x89, 0xd8, 0x1c, 0xc3,
	0x1b, 0xcb, 0x34, 0x5d, 0x89, 0xb8, 0xfb, 0x9f, 0xf7, 0xe6, 0x33, 0x90, 0x9e, 0x4d, 0xf3, 0xbc,
	0xca, 0xfe, 0x61, 0xbd, 0xe5, 0xf3, 0xea, 0x70, 0xc4, 0x5a, 0xec, 0x21, 0xa9, 0xac, 0x33, 0x3c,
	0x03, 0x32, 0x08, 0x92, 0xd3, 0x92, 0x2a, 0x32, 0x60, 0x0b, 0x82, 0xc6, 0x16, 0xf8, 0x0a, 0x58,
	0xd0, 0x2f, 0xc1, 0x72, 0x52, 0x52, 0x85, 0xb1, 0xd8, 0x40, 0x52, 0x69, 0xdf, 0xf2, 0x35, 0xcc,
	0x7a, 0xeb, 0x8c, 0x13, 0x24, 0x67, 0x65, 0xba, 0x5b, 0xca, 0x69, 0x56, 0xe2, 0xa6, 0x8a, 0xac,
	0x78, 0x13, 0xc8, 0x4e, 0x9d, 0x6d, 0x74, 0x57, 0x8f, 0x90, 0x6f, 0x01, 0x9c, 0x37, 0x7d, 0xfd,
	0xe7, 0x74, 0x81, 0x02, 0x26, 0xc7, 0x25, 0xa4, 0x97, 0xdb, 0x5d, 0x77, 0x93, 0x4e, 0x7f, 0xe9,
	0x30, 0x1a, 0xd1, 0xc7, 0x9f, 0xb4, 0x6f, 0x9d, 0x60, 0xdf, 0xa6, 0xf6, 0xad, 0x8a, 0xec, 0x13,
	0x00, 0x00, 0xff, 0xff, 0xc7, 0x9f, 0xae, 0x33, 0x0d, 0x01, 0x00, 0x00,
}
